### ISSUE TITLE
Path to Bravefile dir vs. Path to Bravefile in brave compose

### ISSUE THREAD

**Issue by idroz** [bravetools/bravetools#129]
Right now, brave compose expects the path to a `Bravefile` to be provided under its `services` section. Should we change this to a path of a directory containing a Bravefile?

**Comment by Szubie** [comment]
It is a possibility - I did consider this alternative when working on the feature, and it would also work. 

The reasons I went with the Bravefile itself are:
- It felt more clear - the defaults are read from the file itself, so it felt more natural to pass the file than the directory. 
- More flexibility - passsing the file avoids imposing the one "Bravefile" for one directory rule (which makes more sense during build than deploy). 
- `brave compose` was focused on deployment and when passing a different Bravefile path to `brave deploy` you have to pass the actual filepath. In a way this maintains some consistency with existing commands.

I do think bravetools is a little inconsistent regarding dir paths/file paths though. Personally, I am still considering whether it would be better to pass the full compose file path to `brave compose` rather than the directory containing the file.

**Comment by Szubie** [comment]
Both path to file and path to dir are now accepted - my preference would probably be to use the direct path to the file itself in most cases for clarity, but the dir option maintains compatability and is nice to have.
