### ISSUE TITLE
Show image architecture in brave images

### ISSUE THREAD

**Issue by idroz** [bravetools/bravetools#152]
With remote builds enabled, it is possible to build images with a different architecture to the host system.

It would be good to be able to show image architecture and keep track of it in brave tools.

Maybe we could implement an image naming schema e.g. `image_name-version-arch`

**Comment by Szubie** [comment]
I agree that it would be good to track the architecture as build and deploy CPU architectures may be different.

Doing it in the filename is a nice solution - it keeps the images portable and is important to track. `image_name-version-arch` splits things clearly - LXD public images use something like this too, but with folders - for example: `images/alpine/edge/arm64/default/20220621_13:01/rootfs.tar.xz`.

I am thinking that we should consider separating the schema of the image string as specified by the user in a Bravefile and the filename that is actually stored on disk. This would also mean the user-specified schema could use special separator characters such as '/' for clarity (aligining with LXD public image server), while those are invalid for filenames. 

I think in most cases the user should not need to specify arch manually - when an image is built the arch can be tracked and when deploying the target arch can be queried. Allow manually specifying it would be useful for image hosting LXD servers though.

For the moment bravetools cannot actually import images of a different CPU architecture than the host to its local store since it launches and rebuilds any image it imports, but we can fix that in future if needed.

**Comment by idroz** [comment]
Addressed in #164
